services:
  autoescola_postgres:
    image: postgres:15
    container_name: autoescola_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autoescola
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autoescola"]
      interval: 5s
      timeout: 5s
      retries: 20

  autoescola_pgadmin:
    image: dpage/pgadmin4
    container_name: autoescola_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      autoescola_postgres:
        condition: service_healthy
