version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: autoescola_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autoescola
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d autoescola || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: autoescola_api
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/autoescola
      NODE_ENV: development
    ports:
      - "3000:3000"
    # sem volumes aqui pra N√ÉO sobrescrever o dist dentro da imagem

volumes:
  pgdata:
